// SPDX-License-Identifier: Apache 2.0
// Copyright 2022 - 2023, Syoyo Fujita.
// Copyright 2023 - Present, Light Transport Entertainment Inc.
//
// USDZ(ZIP) writer
//

#include "usdz-writer.hh"

#if !defined(TINYUSDZ_DISABLE_MODULE_USDZ_WRITER)

#include <fstream>
#include <limits>
#include "../../../contrib/tinyusdz/autoclone/tinyusdz_repo-src/src/external/miniz.h"

namespace tinyusdz {
namespace usdz {

bool SaveAsUSDZ(const std::string &filename, const Stage &stage, std::string *warn, std::string *err) {
    // For now, we don't use the Stage object directly for texture extraction
    // as the current Assimp USDZExporter generates USD content as a string.
    // The texture paths are extracted from this string.
    // This function is kept for API compatibility with tinyusdz's usda::SaveAsUSDA.

    if (stage.root_prims().empty()) {
        if (err) {
            (*err) = "Stage is empty\n";
        }
        return false;
    }

    // Generate USD content from the stage (this would typically be done by tinyusdz's usda-writer)
    // For Assimp's current workflow, USD content is generated by USDZExporter.
    // So, this path is not currently used by Assimp's USDZExporter.
    if (err) {
        (*err) = "SaveAsUSDZ(Stage) not fully implemented for Assimp's workflow. Use SaveAsUSDZWithTextures.\n";
    }
    return false;
}

bool SaveAsUSDZWithTextures(const std::string &filename, const std::string &usdContent,
                            const std::map<std::string, std::vector<uint8_t>> &textureDataMap,
                            std::string *warn, std::string *err) {
    std::vector<uint8_t> archive;
    if (!SaveAsUSDZToMemory(usdContent, textureDataMap, archive, warn, err)) {
        return false;
    }

    std::ofstream file(filename, std::ios::binary | std::ios::trunc);
    if (!file) {
        if (err) (*err) += "Failed to open USDZ file for writing: " + filename + "\n";
        return false;
    }

    file.write(reinterpret_cast<const char *>(archive.data()),
            static_cast<std::streamsize>(archive.size()));
    file.close();
    if (!file) {
        if (err) (*err) += "Failed to write USDZ file: " + filename + "\n";
        return false;
    }

    return true;
}

static void WriteLE16(std::vector<uint8_t> &out, uint16_t v) {
    out.push_back(static_cast<uint8_t>(v & 0xFF));
    out.push_back(static_cast<uint8_t>((v >> 8) & 0xFF));
}

static void WriteLE32(std::vector<uint8_t> &out, uint32_t v) {
    out.push_back(static_cast<uint8_t>(v & 0xFF));
    out.push_back(static_cast<uint8_t>((v >> 8) & 0xFF));
    out.push_back(static_cast<uint8_t>((v >> 16) & 0xFF));
    out.push_back(static_cast<uint8_t>((v >> 24) & 0xFF));
}

struct USDZFileEntry {
    std::string name;
    uint32_t localHeaderOffset;
    uint32_t crc32;
    uint32_t size;
    uint16_t extraLen;
};

bool SaveAsUSDZToMemory(const std::string &usdContent,
                        const std::map<std::string, std::vector<uint8_t>> &textureDataMap,
                        std::vector<uint8_t> &outData,
                        std::string *warn, std::string *err) {
    if (usdContent.empty()) {
        if (err) (*err) = "Generated USD content is empty\n";
        return false;
    }

    // Collect all files to package
    struct FileInfo {
        std::string name;
        const uint8_t* data;
        size_t size;
    };

    std::vector<FileInfo> files;
    files.push_back({"model.usda", reinterpret_cast<const uint8_t*>(usdContent.data()), usdContent.size()});
    for (const auto &entry : textureDataMap) {
        if (entry.second.empty()) {
            if (warn) (*warn) += "Texture data is empty: " + entry.first + "\n";
            continue;
        }
        files.push_back({entry.first, entry.second.data(), entry.second.size()});
    }

    // Build USDZ archive manually with 64-byte alignment
    outData.clear();
    constexpr size_t zip64Sentinel32 = std::numeric_limits<uint32_t>::max();
    constexpr size_t zip64Sentinel16 = std::numeric_limits<uint16_t>::max();
    if (files.size() >= zip64Sentinel16) {
        if (err) (*err) = "USDZ archive has " + std::to_string(files.size()) +
                " members; classic ZIP reserves 65535 for ZIP64\n";
        return false;
    }

    size_t projectedSize = 0;
    auto addToProjectedSize = [&projectedSize, err](size_t amount) {
        if (amount > std::numeric_limits<size_t>::max() - projectedSize) {
            if (err) (*err) = "USDZ archive layout exceeds the native address space\n";
            return false;
        }
        projectedSize += amount;
        return true;
    };

    std::vector<USDZFileEntry> entries;
    entries.reserve(files.size());
    for (const auto &file : files) {
        if (file.name.size() > zip64Sentinel16) {
            if (err) (*err) = "USDZ member filename is " + std::to_string(file.name.size()) +
                    " bytes; classic ZIP limit is 65535 bytes\n";
            return false;
        }
        if (file.size >= zip64Sentinel32) {
            if (err) (*err) = "USDZ member is " + std::to_string(file.size) +
                    " bytes; classic ZIP reserves 4294967295 for ZIP64\n";
            return false;
        }
        const size_t localHeaderOffset = projectedSize;
        if (localHeaderOffset >= zip64Sentinel32) {
            if (err) (*err) = "USDZ member local-header offset " + std::to_string(localHeaderOffset) +
                    " requires ZIP64; classic ZIP reserves 4294967295\n";
            return false;
        }
        if (!addToProjectedSize(30) || !addToProjectedSize(file.name.size())) {
            return false;
        }

        size_t padding = 64 - projectedSize % 64;
        if (padding < 4) {
            padding += 64;
        }
        entries.push_back({file.name, static_cast<uint32_t>(localHeaderOffset), 0,
                static_cast<uint32_t>(file.size), static_cast<uint16_t>(padding)});
        if (!addToProjectedSize(padding) || !addToProjectedSize(file.size)) {
            return false;
        }
    }

    const size_t projectedCentralDirOffset = projectedSize;
    if (projectedCentralDirOffset >= zip64Sentinel32) {
        if (err) (*err) = "USDZ central-directory offset " + std::to_string(projectedCentralDirOffset) +
                " requires ZIP64; classic ZIP reserves 4294967295\n";
        return false;
    }
    for (const auto &entry : entries) {
        if (!addToProjectedSize(46) || !addToProjectedSize(entry.name.size())) {
            return false;
        }
    }
    const size_t projectedCentralDirSize = projectedSize - projectedCentralDirOffset;
    if (projectedCentralDirSize >= zip64Sentinel32) {
        if (err) (*err) = "USDZ central-directory size " + std::to_string(projectedCentralDirSize) +
                " requires ZIP64; classic ZIP reserves 4294967295\n";
        return false;
    }
    if (!addToProjectedSize(22)) {
        return false;
    }
    if (!detail::FitsClassicZipArchive(projectedSize)) {
        if (err) (*err) = "USDZ archive is " + std::to_string(projectedSize) +
                " bytes; classic ZIP limit is 4294967295 bytes\n";
        return false;
    }
    if (projectedSize > outData.max_size()) {
        if (err) (*err) = "USDZ archive layout exceeds byte-vector capacity\n";
        return false;
    }
    const uint32_t centralDirOffset = static_cast<uint32_t>(projectedCentralDirOffset);
    const uint32_t centralDirSize = static_cast<uint32_t>(projectedCentralDirSize);
    outData.reserve(projectedSize);

    for (size_t fileIndex = 0; fileIndex < files.size(); ++fileIndex) {
        const auto &file = files[fileIndex];
        USDZFileEntry &entry = entries[fileIndex];
        entry.crc32 = static_cast<uint32_t>(mz_crc32(MZ_CRC32_INIT, file.data, file.size));

        uint16_t extraLen = entry.extraLen;

        // Local file header (30 bytes fixed)
        WriteLE32(outData, 0x04034b50);  // signature
        WriteLE16(outData, 10);          // version needed (1.0)
        WriteLE16(outData, 0);           // flags (none)
        WriteLE16(outData, 0);           // compression (stored)
        WriteLE16(outData, 0);           // mod time
        WriteLE16(outData, 0);           // mod date
        WriteLE32(outData, entry.crc32); // CRC-32
        WriteLE32(outData, entry.size);  // compressed size
        WriteLE32(outData, entry.size);  // uncompressed size
        WriteLE16(outData, static_cast<uint16_t>(file.name.length()));  // filename length
        WriteLE16(outData, extraLen);    // extra field length

        // Filename
        outData.insert(outData.end(), file.name.begin(), file.name.end());

        // Extra field with OpenUSD alignment tag (0x1986)
        {
            uint16_t paddingDataSize = static_cast<uint16_t>(extraLen - 4);
            // Extra field header
            outData.push_back(0x86); outData.push_back(0x19);  // ID = 0x1986
            outData.push_back(static_cast<uint8_t>(paddingDataSize & 0xFF));
            outData.push_back(static_cast<uint8_t>((paddingDataSize >> 8) & 0xFF));
            // Zero padding
            outData.insert(outData.end(), paddingDataSize, 0);
        }

        // File data (uncompressed)
        outData.insert(outData.end(), file.data, file.data + file.size);
    }

    // Central directory
    for (const auto &entry : entries) {
        WriteLE32(outData, 0x02014b50);  // central directory signature
        WriteLE16(outData, 10);          // version made by
        WriteLE16(outData, 10);          // version needed
        WriteLE16(outData, 0);           // flags
        WriteLE16(outData, 0);           // compression
        WriteLE16(outData, 0);           // mod time
        WriteLE16(outData, 0);           // mod date
        WriteLE32(outData, entry.crc32);
        WriteLE32(outData, entry.size);  // compressed size
        WriteLE32(outData, entry.size);  // uncompressed size
        WriteLE16(outData, static_cast<uint16_t>(entry.name.length()));
        WriteLE16(outData, 0);           // extra field length (none in central dir)
        WriteLE16(outData, 0);           // comment length
        WriteLE16(outData, 0);           // disk number start
        WriteLE16(outData, 0);           // internal file attributes
        WriteLE32(outData, 0);           // external file attributes
        WriteLE32(outData, entry.localHeaderOffset);
        outData.insert(outData.end(), entry.name.begin(), entry.name.end());
    }
    // End of central directory record
    WriteLE32(outData, 0x06054b50);  // EOCD signature
    WriteLE16(outData, 0);           // disk number
    WriteLE16(outData, 0);           // disk with central dir
    WriteLE16(outData, static_cast<uint16_t>(entries.size()));
    WriteLE16(outData, static_cast<uint16_t>(entries.size()));
    WriteLE32(outData, centralDirSize);
    WriteLE32(outData, centralDirOffset);
    WriteLE16(outData, 0);           // comment length

    return true;
}

#if defined(_WIN32)
bool SaveAsUSDZ(const std::wstring &filename, const Stage &stage, std::string *warn, std::string *err) {

    (void)warn;
    (void)err;
    (void)stage;
    (void)filename;
    // TODO: Implement WideChar filename version
    return false;
}
#endif

} // namespace usdz
} // namespace tinyusdz

#else

namespace tinyusdz {
namespace usdz {

bool SaveAsUSDZ(const std::string &filename, const Stage &stage, std::string *warn, std::string *err) {
    (void)filename;
    (void)stage;
    (void)warn;

    if (err) {
        (*err) = "USDZ Writer feature is disabled in this build.\n";
    }
    return false;
}

} // namespace usdz
} // namespace tinyusdz
#endif
